// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6W1w2agAennebSrXmxjaoht3Mp8WHyD4',
    appId: '1:971729347463:web:116fcd45f41f23c28f2922',
    messagingSenderId: '971729347463',
    projectId: 'authentication-af768',
    authDomain: 'authentication-af768.firebaseapp.com',
    storageBucket: 'authentication-af768.firebasestorage.app',
    measurementId: 'G-PG58EPQS69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARYnXa4kkJY-t5b0AxxG-i4WIloVm5EaE',
    appId: '1:971729347463:android:e550be4915e2c4cb8f2922',
    messagingSenderId: '971729347463',
    projectId: 'authentication-af768',
    storageBucket: 'authentication-af768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYfVpbW6CWcqvPXLckUMqMhLlTe3CC824',
    appId: '1:971729347463:ios:f66ac88ede914e618f2922',
    messagingSenderId: '971729347463',
    projectId: 'authentication-af768',
    storageBucket: 'authentication-af768.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYfVpbW6CWcqvPXLckUMqMhLlTe3CC824',
    appId: '1:971729347463:ios:f66ac88ede914e618f2922',
    messagingSenderId: '971729347463',
    projectId: 'authentication-af768',
    storageBucket: 'authentication-af768.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6W1w2agAennebSrXmxjaoht3Mp8WHyD4',
    appId: '1:971729347463:web:c7fa9b2418170cc48f2922',
    messagingSenderId: '971729347463',
    projectId: 'authentication-af768',
    authDomain: 'authentication-af768.firebaseapp.com',
    storageBucket: 'authentication-af768.firebasestorage.app',
    measurementId: 'G-L2H8DZ67RC',
  );
}
